name: firebase_apple_auth
description: A new flutter plugin project.
version: 0.1.0
author: Amr Yousef
homepage: https://github.com/amrfarid140/firebase_apple_auth/firebase_apple_auth

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_apple_auth_platform_interface:
    path: ../firebase_apple_auth_platform_interface
  firebase_apple_auth_web:
    path: ../firebase_apple_auth_web
  firebase_auth: ^0.15.3
  firebase_core: ^0.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.amryousef.apple.auth.firebase_apple_auth
        pluginClass: FirebaseAppleAuthPlugin
      ios:
        pluginClass: FirebaseAppleAuthPlugin
      web:
        default_package: firebase_apple_auth_web
