name: firebase_apple_auth_web
description: A new flutter plugin project.
version: 0.0.1
author: Amr Yousef <contact@amryousef.me>
homepage: https://github.com/amrfarid140/firebase_apple_auth/firebase_apple_auth_web

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_apple_auth_platform_interface:
    path: ../firebase_apple_auth_platform_interface
  firebase: ^7.0.0
  js: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppleAuthWeb
        fileName: firebase_apple_auth_web.dart
