name: firebase_apple_auth_platform_interface
description: Platform interface plugin for firebase_apple_auth. This includes API definition which will be implemented for android, ios and web.
version: 0.1.0+1
author: Amr Yousef <contact@amryousef.me>
homepage: https://github.com/amrfarid140/firebase_apple_auth/firebase_apple_auth_platform_interface

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.3
  firebase_core: ^0.4.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
